### ISSUE TITLE
Module not working help

### ISSUE THREAD

**Issue by Rifl33** [daddodev/pimpmyrice#9]
pimp clone module .config/modules/alacritty/
ERROR    module "" already present                                                                                                            
 pimp clone module .config/modules/alacritty/module.yaml 
ERROR    fatal: repository '.config/modules/alacritty/module.yaml' does not exist                                                             
I get this whenever i clone in module.yaml or folder what do i need to clone?
I even tried to do it with your alacritty thing when i cloned it same thing happened

**Comment by daddodev** [comment]
I'm not sure I understand what you're trying to do, anyway clone from local folder is fixed in 9fe08f6

Btw, I made a [discord server](https://discord.gg/TDrSB2wk6c) with an help channel if you want to join
